config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "masterpieces/collection", to: "masterpieces#collection"
  resources :masterpieces do
    resources :bookings, only: [:new, :create, :edit, :update]
  end


  root to: "masterpieces#index"

  resources :bookings, only: [:index, :destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :masterpiece
  belongs_to :user
  has_many :reviews

  validates :start_at, presence: true
  validates :end_at, presence: true
end

app/models/masterpiece.rb
class Masterpiece < ApplicationRecord
  AUTHORIZED_CATEGORIES = ["Paint", "Sculpture", "Photo"]
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  # j'ai proposé 3 types d'oeuvre : peinture, sculture, photo
  validates :category, presence: true, inclusion: { in: AUTHORIZED_CATEGORIES }
  validates :address, presence: true
  # active storage :
  has_one_attached :photo

  include PgSearch::Model
  # multisearchable against: [:title, :description, :category, :address]
  pg_search_scope :search_by_title_description_and_address,
    against: [ :title, :description, :category, :address ], using: { tsearch: { prefix: true } }

  def available?(start_date, end_date)
    bookings.each do |booking|
      return false if (booking.start_at..booking.end_at).overlaps?(start_date.to_date..end_date.to_date)
    end
    return true
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  validates :rating, presence: true, inclusion: { in: %w(0 1 2 3 4 5) }
  validates :content, length: {minimum: 6}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :masterpieces, dependent: :destroy

  validates :name, presence: true

  # active storage :
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @masterpieces = Masterpiece.all
    @bookings_all = Booking.all
    @bookings = []
    # je prends que les bookings qui correspondent à mon user, et je passe
    # uniquement cette liste à la vue
    @bookings_all.each do |booking|
      if booking.user_id == @user.id
        @bookings << booking
      end
    end
  end

  def new
    @masterpiece = Masterpiece.find(params[:masterpiece_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @masterpiece = Masterpiece.find(params[:masterpiece_id])
    @start_date = params[:booking]["start_at"].to_date
    @end_date = params[:booking]["end_at"].to_date

    amount = (@end_date - @start_date + 1) * @masterpiece.price

    if @masterpiece.available?(@start_date, @end_date)
      @booking = Booking.new(user_id: @user.id, masterpiece_id: @masterpiece.id, start_at: @start_date, end_at: @end_date, total_amount: amount)
      if @booking.save
        redirect_to bookings_path, alert: "Artwork successfully booked. Amount : #{amount}€"
      else
        render :new
      end
    else
      redirect_to booking_path(@masterpiece), alert: "Not available. Dates already booked"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @user = current_user
    @masterpiece = Masterpiece.find(params[:masterpiece_id])
    @start_date = params[:booking]["start_at"].to_date
    @end_date = params[:booking]["end_at"].to_date

    amount = (@end_date - @start_date + 1) * @masterpiece.price

    @booking.update(user_id: @user.id, masterpiece_id: @masterpiece.id, start_at: @start_date, end_at: @end_date, total_amount: amount)
    redirect_to bookings_path, alert: "Artwork successfully updated. Amount : #{amount}€"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

end

app/controllers/masterpieces_controller.rb
class MasterpiecesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @masterpieces = Masterpiece.all
    if params[:search].present?
      key_word = params[:search][:search]
      if key_word != ""
        @masterpieces = Masterpiece.search_by_title_description_and_address(params[:search][:search])
      end
      if params[:max_price].present?
        @masterpieces = @masterpieces.where("price <= ?", params[:max_price])
      end
      if params[:category].present?
        @masterpieces = @masterpieces.where(category: params[:category])
      end
      if params[:search][:start_at].present? && params[:search][:end_at].present?
        @masterpieces = @masterpieces.select do |masterpiece|
          masterpiece.available?(params[:search][:start_at], params[:search][:end_at])
        end
      end
    end
  end

  def show
    @users = User.all
    @masterpiece = Masterpiece.find(params[:id])
  end

  def create
    @user = current_user
    @masterpiece = Masterpiece.new(masterpiece_params)
    @masterpiece.user_id = @user.id
    if @masterpiece.save
      redirect_to masterpieces_collection_path, alert: "The new Artwork has been added successfully."
    else
      render :collection, status: :unprocessable_entity
    end
  end

  def destroy
    @masterpiece = Masterpiece.find(params[:id])
    @masterpiece.destroy
    redirect_to masterpieces_collection_path, status: :see_other
  end

  def collection
    @users = User.all
    @user = current_user
    @masterpieces_all = Masterpiece.all
    masterpieces = Masterpiece.all
    @masterpieces = []
    masterpieces.each do |masterpiece|
      if masterpiece.user_id == @user.id
        @masterpieces << masterpiece
      end
    end
    @bookings = Booking.all
    @new_masterpiece = Masterpiece.new
    @bookings_user = []
    @bookings.each do |booking|
      if booking.user_id == @user.id
        @bookings_user << booking
      end
    end
  end

  private

  def set_masterpiece
  end

  def masterpiece_params
    params.require(:masterpiece).permit(:title, :description, :price, :address, :category, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
  <%= simple_form_for [masterpiece, booking] do |f| %>

    <div class="cardbookingdates">
      <div class="cardbookingselection_left">
        <div class="inputadj">
          <%= f.input :start_at, label: "Start from", as: :string, input_html: { data: { controller: "datepicker" , action: "change->datepicker#fire", target:"togglableElement"}, value: params[:booking_start_at]}, id:"startdate"%>
        </div>
      </div>
      <div class="cardbookingselection_right">
        <div class="inputadj">
          <%= f.input :end_at, label: "To", as: :string, input_html: { data: { controller: "datepicker" , action: "change->datepicker#fire", target:"togglableElement"}, value: params[:booking_end_at]}, id:"enddate"%>
        </div>
      </div>
    </div>

    <% if params[:booking_start_at].present? && params[:booking_end_at].present? %>
      <% nbdays = (params[:booking_end_at].to_date - params[:booking_start_at].to_date).to_s.split("/").first.to_i %>
    <% else %>
      <% nbdays = 1 %>
    <% end %>

    <div class="bookcard">
      <div class="booktext">
        <p>Duration : <b id="night"><%= nbdays %></b> days </p>
        <p>Price per day : <b id="price"><%= masterpiece.price %></b> € </p>
        <p>Total amount : <b id="totalprice"><%= masterpiece.price * nbdays %></b> € </p>
      </div>
      <div class="bookbtn">
        <div class="form-group mt-3">
        <%= f.submit 'Book now !', class: 'btnSubmitSmall' %>
        </div>
      </div>
    </div>

  <% end %>



<%# on pourra prévoir ici un peu de js pour afficher le prix total en fonction du nombre de jours sélectionnés %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/bookings/_formupdate.html.erb
<div class="container">
<div data-controller="update-booking">
    <%= simple_form_for [masterpiece, booking] do |f| %>

    <div class="cardbookingdates">
      <div class="cardbookingselection_left">
        <div class="inputadj">
          <%= f.input :start_at, label: "Start from", as: :string, input_html: { data: { controller: "datepicker", action: "change->update-booking#update", update_booking_target:"bookingStart"}}%>
        </div>
      </div>
      <div class="cardbookingselection_right">
        <div class="inputadj">
          <%= f.input :end_at, label: "To", as: :string, input_html: { data: { controller: "datepicker", action: "change->update-booking#update", update_booking_target:"bookingEnd"}}%>
        </div>
      </div>
    </div>

      <% nbdays = booking.end_at.to_date - booking.start_at.to_date + 1 %>

    <div class="bookcard">
      <div class="booktext">
        <p>Duration : <b data-update-booking-target="days"><%= nbdays.to_i %></b> days </p>
        <p>Price per day : <b data-update-booking-target="price"><%= masterpiece.price %></b> € </p>
        <p>Total amount : <b data-update-booking-target="totalprice"><%= masterpiece.price * nbdays%></b> € </p>
      </div>
      <div class="bookbtn">
        <div class="form-group mt-3">
        <%= f.submit 'Book now !', class: 'btnSubmitSmall' %>
        </div>
      </div>
    </div>

  <% end %>



<%# on pourra prévoir ici un peu de js pour afficher le prix total en fonction du nombre de jours sélectionnés %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

</div>
</div>

app/views/bookings/new.html.erb
<div class="container centerContainer ">
  <div class="logForm">

  <div>
  <h2>Want to book <%= @masterpiece.title %> ?</h2>
  </div>

  <div>
  <%= render "form", masterpiece: @masterpiece, booking: @booking %>
  </div>

  <div class="form-group mt-3">
  <%= link_to 'Back to Artwork', masterpiece_path(@masterpiece.id), class: 'btnSubmit4' %>
  </div>

</div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_include_tag 'slider' %>  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

 <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/masterpieces/_booking.html.erb
<% bookings.each do |booking|  %>
  <% if booking.masterpiece_id == masterpiece.id %>
    <div class="container-booking">
      <ul class="booking-details m-3">
            <li class="list-group-item">
              <p class="mb-2">Tenant : <%= users.find(booking.user_id).name %></p>
              <p class="mb-2">Contact : <%= users.find(booking.user_id).email %></p>
              <p class="mb-2">Price : <%= booking.total_amount %></p>
              <p class="mb-2">Start from : <%= booking.start_at.to_date %></p>
              <p class="mb-2">To : <%= booking.end_at.to_date %></p>
            </li>
          <%= link_to 'Cancel booking', booking_path(booking.id), class: 'btn btn-ghost mt-3', data: {turbo_method: :delete, turbo_confirm: "Do you want to cancel this booking?"} %>
      </ul>
    </div>
  <% end  %>
<% end  %>

app/views/masterpieces/_cardbooking.html.erb
<%#<div class="cardbooking">
<%#  <h2><b><%= @masterpiece.price %> <%# €</b> per day </h1>
<%#  <div class="cardbookingdates">
<%#    <div class="cardbookingselection_left">
<%#      <h2><b>START FROM</b></h2>
<%#      <h3><%= Date.today %><%# </h3>
<%#    </div>
<%#    <div class="cardbookingselection_right">
<%#      <h2><b>TO</b></h2>
<%#      <h3><%= Date.today + 1 %><%# </h3>
<%#   </div>
<%#  </div>
<%#  <%= link_to 'I want to book it', new_masterpiece_booking_path(params[:id]), class: 'cardbookingbtn' %>
<%#</div>%>
<%#<form action="<%= url_for([@masterpiece, @booking]) %><%#" method="get">%>
<%#<%= link_to 'I want to book it', new_masterpiece_booking_path(params[:id], start_at:params[:booking_start_at], end_at:params[:booking_end_at]), class: 'cardbookingbtn' %>


<% today = Date.today %>
<% tommorrow = Date.today + 1 %>
<div class="cardbooking">
  <h2><b><%= @masterpiece.price %> €</b> per day </h1>
  <form action="<%= new_masterpiece_booking_path(params[:id], start_at:params[:booking_start_at], end_at:params[:booking_end_at]) %>" method="get">
  <div class="cardbookingdates">
    <div class="cardbookingselection_left">
      <h2><b>START FROM</b></h2>
      <div class="inputadj">
        <input type="text" id="booking_start_at" name="booking_start_at" size ="10" data-controller="datepicker" class ="center" placeholder="<%= today %>" value = "<%= params[:start_at] %>">
      </div>
    </div>
    <div class="cardbookingselection_right">
      <h2><b>TO</b></h2>
      <div class="inputadj">
        <input type="text" id="booking_end_at" name="booking_end_at" size ="10" data-controller="datepicker" class ="center" placeholder= "<%= tommorrow %>" value = "<%= params[:end_at] %>">
      </div>
    </div>
  </div>
  <input type="submit" value="I want to book it" class="cardbookingbtn" data-controller="pricecalculation">
  </form>
</div>

app/views/masterpieces/_cardmasterpieces.html.erb
<% masterpieces.each do |masterpiece|  %>
    <div class="home-card-masterpiece">
      <h3>
        <%= masterpiece.title %>
      </h3>
      <% if (params[:search].present? && params[:search][:start_at].present? && params[:search][:end_at].present?) %>
        <%= link_to masterpiece_path(masterpiece,start_at:params[:search][:start_at],end_at:params[:search][:end_at]) do %>
          <%= cl_image_tag masterpiece.photo.key %>
        <% end %>
      <% else %>
        <%= link_to masterpiece_path(masterpiece) do %>
          <%= cl_image_tag masterpiece.photo.key %>
        <% end %>
      <% end %>
    </div>
<%end%>

app/views/masterpieces/_form.html.erb
<%= simple_form_for masterpiece do |f| %>
    <div class="form-group mt-3 ">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :category %>
      <%= f.select :category, Masterpiece::AUTHORIZED_CATEGORIES, {}, { class: 'form-control' } %>
    </div>

    <div class="form-group mt-3">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-group mt-3">
      <%= f.submit 'Save', class: 'btn btn-ghost' %>
    </div>
  <% end %>

app/views/masterpieces/collection.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col">
      <h1 class="mt-3">Listings</h1>

 <!-- Button trigger modal -->
<button type="button" class="btn btn-ghost my-5" data-bs-toggle="modal" data-bs-target="#newArtworkModal">
  Publish a new artwork
</button>

<!-- Modal -->
<div class="modal fade" id="newArtworkModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newArtworkModalLabel">Publish a New Artwork</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "form", masterpiece: @new_masterpiece %>
      </div>
    </div>
  </div>
</div>

        <div class="card-product mb-5">
            <div class="card-product-infos">
              <h2>Review the reservations for your art pieces</h2>
              <p>Do you have more artworks to offer? Then, post a new listing!</p>
            </div>
          <%= image_tag "beau-graffiti-cubisme.jpg" %>
        </div>

      <div class="user-cards-masterpiece my-5">
      <% @masterpieces.each do |masterpiece|  %>
        <div class="user-card-masterpiece mt-5">
          <%= cl_image_tag masterpiece.photo.key, class: "avatar-large" %>
          <div class="user-masterpiece-content">
            <p><%= masterpiece.title%></p>
            <p><small>Booking in progress : <%=masterpiece.bookings.count%> </small></p>
          </div>
          <div class="user-masterpiece-actions">
            <%= link_to "Cancel", masterpiece_path(masterpiece.id), class: 'btn btn-ghost', data: {turbo_method: :delete, turbo_confirm: "Do you really want to cancel this artwork?"} %>
            <button type="button" class="btn btn-ghost mt-3" data-bs-toggle="modal" data-bs-target="#myModal<%= masterpiece.id %>">
              Bookings
            </button>
          </div>

              <div class="modal" id="myModal<%= masterpiece.id %>" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-body">
                        <%= render "booking", bookings: @bookings, users: @users, masterpiece: masterpiece %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-ghost" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>

        </div>
      <% end %>
      </div>

          <div data-controller="toggle-add-masterpiece" class="my-3 row justify-content-center">
            <button class="btn btn-ghost my-3 w-25" data-action="click->toggle-add-masterpiece#fire">Key statistics</button>
            <div data-toggle-add-masterpiece-target="togglableElement" class="d-none">
                <%= render "shared/amount", masterpieces: @masterpieces_all, bookings_user: @bookings_user, bookings_all: @bookings %>
            </div>
          </div>

    </div>
  </div>
</div>

app/views/masterpieces/index.html.erb
<section class="slider">
  <div class="slide" style="background-image: url('https://images.unsplash.com/photo-1652766825080-88818e6509b6?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
    <div class="content">
      <h2>Searching for an artwork ?<br>Opt for renting</h2>
      <p>Rent today and enjoy the space, a moment, a unique creation to contemplate every day.<br>Painting, Drawing, Poster, Photography, ... Discover the works of our artits.</p>
      <a href="#" class="main-btn" id="btn-slider">Discover the renting</a>
    </div>
  </div>
  <div class="slide" style="background-image: url('https://images.unsplash.com/photo-1576926241721-4b830531f667?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
    <div class="content">
      <h2>Vintage posters</h2>
      <p>Our top-of-the-line selection! World maps, graphic posters, and striking paintings... <br>The possibilities are endless to dress up and personalize your walls.</p>
      <a href="#" class="main-btn">Explore the selection</a>
    </div>
  </div>
  <div class="slide" style="background-image: url('https://images.unsplash.com/photo-1652766825080-88818e6509b6?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
    <div class="content">
      <h2>The current artists</h2>
      <p>Vibrant paintings that resonate with emotion, canvas artworks spanning various styles, including street art movement. Our collection invites you to explore the multiple facets of contemporary artistic expression.</p>
      <a href="#" class="main-btn">Explore the selection</a>
    </div>
  </div>
  <div class="slide" style="background-image: url('https://images.unsplash.com/photo-1578926078640-668b1fb75403?q=80&w=2866&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
    <div class="content">
      <h2>The watercolors</h2>
      <p>Whether to brighten up your interior or to give an unforgettable gift, our watercolors will charm your heart and awaken your artistic sensibility.</p>
      <a href="#" class="main-btn">Explore the selection</a>
    </div>
  </div>

  <div class="dots-container">
      <span class="dot" data-index="0"></span>
      <span class="dot" data-index="1"></span>
      <span class="dot" data-index="2"></span>
      <span class="dot" data-index="3"></span>
  </div>
</section>

  <section>
    <div class="show-list">
      <div class="head">
        <div class="text-content">
          <h3>Our artworks</h3>
          <p>Discover the artworks that our customers love.</p>
        </div>
        <div class="link">
          <a href="#" class="secondary-btn">Discover the collection</a>
        </div>
      </div>
   </div>
  </section>


<section>
<div class="container">
<!-- Button trigger modal -->
<button type="button" class="btn btn-ghost mb-5" data-bs-toggle="modal" data-bs-target="#homeSearchModal" data-bs-backdrop="false">
  Search masterpiece
</button>

<!-- Modal -->
<div class="modal" id="homeSearchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="homeSearchModalLabel">Find an artwork to rent quickly!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "searchform" %>
      </div>
    </div>
  </div>
</div>
<%# fin modal %>


<%# cards des oeuvres %>
  <div class="home-cards-masterpieces">
    <%= render "cardmasterpieces", masterpieces: @masterpieces %>
  </div>
</div>

</section>

<%# <h2>Ancienne version</h2>
    <div class="container">
      <div class="row">
        <div class="col">
          <h1>Our artworks</h1>
          <ul class="list-group">
            <% @masterpieces.each do |masterpiece|
              <li class="list-group-item mt-3">
                <% if (params[:search].present? && params[:search][:start_at].present? && params[:search][:end_at].present?)
                  <%= link_to masterpiece.title, masterpiece_path(masterpiece,start_at:params[:search][:start_at],end_at:params[:search][:end_at])
                  <%= masterpiece_path(masterpiece,start_at:params[:search][:start_at],end_at:params[:search][:end_at]) do
                    <%= cl_image_tag masterpiece.photo.key, height: 300, width: 400, crop: :fill
                  <% end
                <% else
                  <%= link_to masterpiece_path(masterpiece) do
                    <%= cl_image_tag masterpiece.photo.key, height: 300, width: 400, crop: :fill
                  <% end
                  <%= link_to masterpiece.title, masterpiece_path(masterpiece)
                <% end
              </li>
            <% end
          </ul>

        </div>
      </div>
    </div> %>
<%# fin des cards oeuvre %>


  <%# <section>
    <div class="nav-blocks">
      <div class="left-blocks">
        <div class="nav-block__item">
          <h3>Paintings</h3>
          <img src="https://images.unsplash.com/photo-1548685913-70235e21eab2?q=80&w=2889&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Bloc-1">
        </div>
        <div class="nav-block__item">
          <h3>Photographies</h3>
          <img src="https://images.unsplash.com/photo-1519668752166-ebdbfe986afd?q=80&w=2468&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
        </div>
      </div>

      <div class="right-blocks">
        <div class="nav-block__item">
          <h3>Posters & Prints</h3>
          <img src="https://www.fleux.com/cdn/shop/products/aperol-negroni_1200x.jpg?v=1675471292" alt="">
        </div>
        <div class="nav-block__item">
          <h3>Drawings & Illustrations</h3>
          <img src="https://images.unsplash.com/photo-1589637458063-7b054f0c18ab?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
        </div>
        <div class="nav-block__item">
          <h3>Artists</h3>
          <img src="https://images.unsplash.com/photo-1500628550463-c8881a54d4d4?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
        </div>
      </div>
    </div>
  </section> %>

  <section>
    <div class="pre-footer"></div>
  </section>

  <section>
    <div class="footer"></div>
  </section>

app/views/masterpieces/show.html.erb
<div class="container">

      <div class="showinfos">
        <div class="colonne showimage">
          <%= cl_image_tag @masterpiece.photo.key, crop: :fill %>
        </div>

        <div class="colonne">
          <h1><b><%= @masterpiece.title %></b></h1>
          <div class="infos grey">
            <div>
              <p><strong>By : </strong> <u><%= @users.find(@masterpiece.user_id).name %></u></p>
            </div>
            <div>
              <p><%= @masterpiece.category %></p>
            </div>
          </div>
          <div class="centerH">
            <%= render "cardbooking", bookings: @bookings, users: @users, masterpiece: @masterpiece %>
          </div>

          <div class="displayinfos">
            <div class="description">
              <p><strong>Description:</strong> <%= @masterpiece.description %></p>
            </div>
            <div class="addressCont">
              <div class="address">
                <div class="addresseL"><p><i class="fa-solid fa-location-dot pin"></i></div>
                <div class="addresseR"><%= @masterpiece.address %></p></div>
              </div>
            </div>

          </div>

        </div>
      </div>


<%#
  <div class="btnback">
    <%= link_to 'Back to masterpieces', masterpieces_path, class: 'cardbookingbtn' %>
<%#  </div>%>

</div>